USE db_arcadia;
DELETE FROM Musique;
DELETE FROM Livre;

INSERT INTO Musique (titre, artiste, genre, album, format, prix, disponibilite, duree, chemin_audio, photo_artiste) VALUES
/*Gunna*/
('Collage', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:28', 'musiques\\One_of_Wun_Gunna\\Collage.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('One of Wun', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:25', 'musiques\\One_of_Wun_Gunna\\one_of_wun.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Neck on a Yacht', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:36', 'musiques\\One_of_Wun_Gunna\\neck_on_a_yacht.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Whatsapp (Wassam)', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:58', 'musiques\\One_of_Wun_Gunna\\whatsapp_(wassam).webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Hakuna Matata', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:08', 'musiques\\One_of_Wun_Gunna\\hakuna_matata.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Prada Dem', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:46', 'musiques\\One_of_Wun_Gunna\\prada_dem.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Treesh', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:13', 'musiques\\One_of_Wun_Gunna\\treesh.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('On One Tonight', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:01:31', 'musiques\\One_of_Wun_Gunna\\on_one tonight.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Back in the A', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:54', 'musiques\\One_of_Wun_Gunna\\back_in_the_a.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Trio', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:01:57', 'musiques\\One_of_Wun_Gunna\\trio.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Still Prevail', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:03:13', 'musiques\\One_of_Wun_Gunna\\still_prevail.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Blackjack', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:03:25', 'musiques\\One_of_Wun_Gunna\\blackjack.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('$$$', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:03:02', 'musiques\\One_of_Wun_Gunna\\$$$.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Clear My Rain', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:03:04', 'musiques\\One_of_Wun_Gunna\\clear_my_rain.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Conscience', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:24', 'musiques\\One_of_Wun_Gunna\\conscience.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('The Time', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:02:52', 'musiques\\One_of_Wun_Gunna\\the_time.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),
('Time Reveals, Be Careful What You Wish For', 'Gunna', 'Rap', 'One of Wun', 'cd', NULL, 'En stock', '00:06:36', 'musiques\\One_of_Wun_Gunna\\time_reveals_be_careful_what_you_wish_for.webm','\\musiques\\One_Of_Wun_Gunna\\Gunna.png'),

/*Celine Dion*/
('The Reason', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:05:03', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\The_Reason.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Immortality (feat. Bee Gees)', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:14', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Immortality_(feat._Bee_Gees).webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Treat Her Like a Lady (feat. Diana King & Brownstone)', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:07', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Treat_Her_Like_a_Lady_(feat._Diana_King_&_Brownstone).webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Why Oh Why', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:53', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Why_Oh_Why.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Love Is on the Way', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:28', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Love_Is_on_the_Way.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Tell Him (duet with Barbra Streisand)', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:53', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Tell_Him_(duet_with_Barbra_Streisand).webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Amar haciendo el amor', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:13', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Amar_haciendo_el_amor.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('When I Need You', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:13', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\When_I_Need_You.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Miles to Go (Before I Sleep)', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:43', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Miles_to_Go_(Before_I_Sleep).webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Us', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:05:48', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Us.m4a','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Just a Little Bit of Love', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:29', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Just_a_Little_Bit_of_Love.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('My Heart Will Go On', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:42', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\My_Heart_Will_Go_On.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Where Is the Love', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:57', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Where_Is_the_Love.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Be the Man', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:41', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Be_the_Man.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('I Have You Then I Love You (duet with Luciano Pavarotti)', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:04:41', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\I_Have_You_Then_I_Love_You_(duet_with_Luciano_Pavarotti).webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),
('Let_s Talk About Love', 'Céline Dion', 'Pop', 'Let_s Talk About Love', 'cd', NULL, 'En stock', '00:05:14', 'musiques\\Let_s_Talk_About_Love_Celine_Dion\\Let_s_Talk_About_Love.webm','\\musiques\\Let_s_Talk_About_Love_Celine_Dion\\celine_dion.jpg'),

/*Kid Cudi*/
('In My Dreams (Cudder Anthem)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:19', 'musiques\\Man_on_the_Moon_Kid_Cudi\\in_my_dreams.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Soundtrack 2 My Life', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:56', 'musiques\\Man_on_the_Moon_Kid_Cudi\\soundtrack_2_my_life.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Simple As...', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:02:31', 'musiques\\Man_on_the_Moon_Kid_Cudi\\simple_as.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Solo Dolo (Nightmare)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:25', 'musiques\\Man_on_the_Moon_Kid_Cudi\\solo_dolo.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Heart of a Lion (Kid Cudi Theme Music)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:21', 'musiques\\Man_on_the_Moon_Kid_Cudi\\heart_of_a_lion.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('My World', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:03', 'musiques\\Man_on_the_Moon_Kid_Cudi\\my_world.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Day N Nite (Nightmare)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:41', 'musiques\\Man_on_the_Moon_Kid_Cudi\\day_n_nite.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Sky Might Fall', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:40', 'musiques\\Man_on_the_Moon_Kid_Cudi\\sky_might_fall.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Enter Galactic (Love Connection Part I)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:20', 'musiques\\Man_on_the_Moon_Kid_Cudi\\enter_galactic.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Alive (Nightmare)', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:06', 'musiques\\Man_on_the_Moon_Kid_Cudi\\alive.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Cudi Zone', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:19', 'musiques\\Man_on_the_Moon_Kid_Cudi\\cudi_zone.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Make Her Say', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:36', 'musiques\\Man_on_the_Moon_Kid_Cudi\\make_her_say.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Pursuit of Happiness', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:04:55', 'musiques\\Man_on_the_Moon_Kid_Cudi\\pursuit_of_happiness.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Hyyerr', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:32', 'musiques\\Man_on_the_Moon_Kid_Cudi\\hyyerr.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),
('Up Up & Away', 'Kid Cudi', 'Hip Hop', 'Man on the Moon: The End of Day', 'cd', NULL, 'En stock', '00:03:47', 'musiques\\Man_on_the_Moon_Kid_Cudi\\up_up_and_away.webm', '\\musiques\\Man_on_the_Moon_Kid_Cudi\\Kid_Cudi.jpg'),

/*Kendrick Lamar*/
('Bitch, Don''t Kill My Vibe', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:05:10', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\bitch_dont_kill_my_vibe.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Backseat Freestyle', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:03:32', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\backseat_freestyle.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('The Art of Peer Pressure', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:05:24', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\the_art_of_peer_pressure.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Money Trees', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:06:26', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\money_trees.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Poetic Justice', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:05:00', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\poetic_justice.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Good Kid', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:03:34', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\good_kid.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('m.A.A.d City', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:05:50', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\maad_city.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Swimming Pools (Drank)', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:04:07', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\swimming_pools.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Sing About Me, I''m Dying of Thirst', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:12:04', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\sing_about_me_im_dying_of_thirst.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Real', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:07:23', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\real.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),
('Compton', 'Kendrick Lamar', 'Hip Hop', 'Good Kid, M.A.A.D City', 'cd', NULL, 'En stock', '00:04:08', 'musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\compton.webm', '\\musiques\\Good_Kid_M.A.A.D_City_Kendrick_Lamar\\Kendrick_Lamar.jpg'),

('Speak to Me', 'Pink Floyd', 'Rock Progressif', 'The Dark Side of the Moon', 'cd', NULL, 'En stock', '00:01:30', 'musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\speak_to_me.webm', '\\musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\Pink_Floyd.png'),
('Breathe', 'Pink Floyd', 'Rock Progressif', 'The Dark Side of the Moon', 'cd', NULL, 'En stock', '00:02:45', 'musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\breathe.webm', '\\musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\Pink_Floyd.png'),
('On the Run', 'Pink Floyd', 'Rock Progressif', 'The Dark Side of the Moon', 'cd', NULL, 'En stock', '00:03:35', 'musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\on_the_run.webm', '\\musiques\\The_Dark_Side_of_the_Moon_Pink_Floyd\\Pink_Floyd.png'),

/*Pop*/
/*Adele*/
('Rolling in the Deep', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:03:48', 'musiques\\21_Adele\\rolling_in_the_deep.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Someone Like You', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:47', 'musiques\\21_Adele\\someone_like_you.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Set Fire to the Rain', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:02', 'musiques\\21_Adele\\set_fire_to_the_rain.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Rumour Has It', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:03:43', 'musiques\\21_Adele\\rumour_has_it.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Turning Tables', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:10', 'musiques\\21_Adele\\turning_tables.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Don''t You Remember', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:03', 'musiques\\21_Adele\\dont_you_remember.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('He Won''t Go', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:38', 'musiques\\21_Adele\\he_wont_go.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('Take It All', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:03:49', 'musiques\\21_Adele\\take_it_all.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('I''ll Be Waiting', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:04:01', 'musiques\\21_Adele\\ill_be_waiting.webm', '\\musiques\\21_Adele\\Adele.jpg'),
('One and Only', 'Adele', 'Pop', '21', 'cd', NULL, 'En stock', '00:05:48', 'musiques\\21_Adele\\one_and_only.webm', '\\musiques\\21_Adele\\Adele.jpg'),

/*Madonna*/
('Drowned World / Substitute for Love', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:09', 'chemin/vers/Drowned_World.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Swim', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:01', 'chemin/vers/Swim.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Ray of Light', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:22', 'chemin/vers/Ray_of_Light.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Candy Perfume Girl', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '4:37', 'chemin/vers/Candy_Perfume_Girl.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Skin', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '6:22', 'chemin/vers/Skin.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Nothing Really Matters', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '4:28', 'chemin/vers/Nothing_Really_Matters.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Sky Fits Heaven', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '4:48', 'chemin/vers/Sky_Fits_Heaven.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Shanti / Ashtangi', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '4:29', 'chemin/vers/Shanti_Ashtangi.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Frozen', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '6:08', 'chemin/vers/Frozen.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('The Power of Good-Bye', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '4:12', 'chemin/vers/The_Power_of_Good_Bye.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('To Have and Not to Hold', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:23', 'chemin/vers/To_Have_and_Not_to_Hold.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Little Star', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:19', 'chemin/vers/Little_Star.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),
('Mer Girl', 'Madonna', 'Pop', 'Ray of Light', 'CD', NULL, 'En stock', '5:32', 'chemin/vers/Mer_Girl.webm', '\\musiques\\Ray_of_Light_Madonna\\Ray_of_Light_Madonna.png'),


('Holiday', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '4:01', 'chemin/vers/Holiday.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Lucky Star', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:31', 'chemin/vers/Lucky_Star.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Borderline', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '4:02', 'chemin/vers/Borderline.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Like a Virgin', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:13', 'chemin/vers/Like_a_Virgin.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Material Girl', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:53', 'chemin/vers/Material_Girl.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Crazy For You', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:48', 'chemin/vers/Crazy_For_You.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Into the Groove', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '4:05', 'chemin/vers/Into_the_Groove.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Live to Tell', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '5:18', 'chemin/vers/Live_to_Tell.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Papa Dont Preach', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '4:11', 'chemin/vers/Papa_Dont_Preach.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Open Your Heart', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:51', 'chemin/vers/Open_Your_Heart.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('La Isla Bonita', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:50', 'chemin/vers/La_Isla_Bonita.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Like a Prayer', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '5:51', 'chemin/vers/Like_a_Prayer.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Express Yourself', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '4:05', 'chemin/vers/Express_Yourself.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Cherish', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '3:53', 'chemin/vers/Cherish.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Vogue', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '5:20', 'chemin/vers/Vogue.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Justify My Love', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '5:00', 'chemin/vers/Justify_My_Love.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),
('Rescue Me', 'Madonna', 'Pop', 'The Immaculate Collection', 'CD', NULL, 'En stock', '5:30', 'chemin/vers/Rescue_Me.webm', 'musiques\\immaculate_madonna\\immaculate_madonna.jpg'),

/*French music*/
/*Aya nakamura*/
('Corazon', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:46', 'musiques\\Aya_nakamura_dnk\\Corazon.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Baby', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:43', 'musiques\\Aya_nakamura_dnk\\Baby.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Daddy', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:03:18', 'musiques\\Aya_nakamura_dnk\\Daddy.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('SMS', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:34', 'musiques\\Aya_nakamura_dnk\\SMS.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Tous les jours', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:51', 'musiques\\Aya_nakamura_dnk\\Tous_les_jours.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('T''as peur', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:03:36', 'musiques\\Aya_nakamura_dnk\\T_as_peur.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Beleck', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:20', 'musiques\\Aya_nakamura_dnk\\Beleck.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Cadeau (feat. Tiakola)', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:31', 'musiques\\Aya_nakamura_dnk\\Cadeau.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('J''ai mal', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:34', 'musiques\\Aya_nakamura_dnk\\J_ai_mal.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Coller', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:52', 'musiques\\Aya_nakamura_dnk\\Coller.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Le goût', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:48', 'musiques\\Aya_nakamura_dnk\\le_goût.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Chacun (feat. Kim)', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:03:06', 'musiques\\Aya_nakamura_dnk\\Chacun.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Haut niveau', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:03:03', 'musiques\\Aya_nakamura_dnk\\Haut_niveau.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Bloqué', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:35', 'musiques\\Aya_nakamura_dnk\\Bloque.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),
('Fin', 'Aya Nakamura', 'French music', 'DNK', NULL, NULL, NULL, '00:02:25', 'musiques\\Aya_nakamura_dnk\\Fin.webm', 'musiques\\Aya_nakamura_dnk\\DNK.jpg'),


/*MHD*/
('Petit coeur', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:22', 'musiques\\mhd_mansa\\Petit_coeur.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Elle', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:16', 'musiques\\mhd_mansa\\Elle.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('MHD feat. Tiakola - Pololo', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:15', 'musiques\\mhd_mansa\\Pololo.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Beyoncé', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:31', 'musiques\\mhd_mansa\\Beyonce.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('MHD - AFRO TRAP Part.11 (King Kong)', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:35', 'musiques\\mhd_mansa\\5-Afro-Trap-Part.-11-King-Kong.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Jamais', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:38', 'musiques\\mhd_mansa\\Jamais.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Fiesta', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:46', 'musiques\\mhd_mansa\\Fiesta.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('FNR', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:25', 'musiques\\mhd_mansa\\FNR.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('MHD - Sagacité', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:54', 'musiques\\mhd_mansa\\Sagacite.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Illimité', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:41', 'musiques\\mhd_mansa\\Illimite.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Wonder Mama', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:03:17', 'musiques\\mhd_mansa\\Wonder_Mama.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),
('Tout gâcher', 'MHD', 'French music', 'Mansa', NULL, NULL, NULL, '00:02:51', 'musiques\\mhd _mansa\\14-Tout-gâcher.mp3', 'musiques\\mhd _mansa\\mhd.jpg'),

/*Freeze corleone*/
('MW2', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:04:48', 'musiques\\freeze_corleone_voldemort\\01-MW2.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Isshin Ashina', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:04:54', 'musiques\\freeze_corleone_voldemort\\02-Isshin-Ashina.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Shavkat', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:40', 'musiques\\freeze_corleone_voldemort\\03-Shavkat.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Amérique du sud', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:32', 'musiques\\freeze_corleone_voldemort\\04-Amérique-du-sud.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Ancelotti', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:41', 'musiques\\freeze_corleone_voldemort\\05-Ancelotti.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Tse Chi Lop', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:19', 'musiques\\freeze_corleone_voldemort\\06-Tse-Chi-Lop.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Kpop', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:02', 'musiques\\freeze_corleone_voldemort\\07-Kpop.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
("L\'homme méthode", 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:11', 'musiques\\freeze_corleone_voldemort\\08-Lhomme-méthode.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Bill Clinton', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:30', 'musiques\\freeze_corleone_voldemort\\09-Bill-Clinton.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Voldemort', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:49', 'musiques\\freeze_corleone_voldemort\\10-Voldemort.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Argent noir part. 3', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:02:58', 'musiques\\freeze_corleone_voldemort\\11-Argent-noir-part.-3.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Jour de plus', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:30', 'musiques\\freeze_corleone_voldemort\\12-Jour-de-plus.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
('Lamborghini bénie', 'Freeze Corleone', 'French music', 'ADC', NULL, NULL, NULL, '00:03:54', 'musiques\\freeze_corleone_voldemort\\\13-Lamborghini-bénie.mp3', 'musiques\\freeze_corleone_voldemort\\voldemort.png'),
/*Osirus jack*/
('Killuavie', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:40', 'musiques/Osirus_Jack/Killuavie.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Kyrie Irving', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:53', 'musiques/Osirus_Jack/Kyrie_Irving.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Connectés (feat. Slim C)', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:03:01', 'musiques/Osirus_Jack/Connectes.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('OSS', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:40', 'musiques/Osirus_Jack/OSS.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Lyoto Machida', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:18', 'musiques/Osirus_Jack/Lyoto_Machida.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Normandie', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:44', 'musiques/Osirus_Jack/Normandie.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Bolo Yeung (feat. Alpha Wann)', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:58', 'musiques/Osirus_Jack/Bolo_Yeung.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('5000L', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:03:30', 'musiques/Osirus_Jack/5000L.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Dangote', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:03:12', 'musiques/Osirus_Jack/Dangote.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Onde de choc, pt. II (feat. DOC OVG, Black Jack OBS)', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:04:07', 'musiques/Osirus_Jack/Onde_de_choc.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Sous-marin', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:44', 'musiques/Osirus_Jack/Sous-marin.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Neuralink (feat. Freeze Corleone)', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:43', 'musiques/Osirus_Jack/Neuralink.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),
('Nicolas III', 'Osirus Jack', 'French music', 'Tsar Noir', 'webm', NULL, 'En stock', '00:02:51', 'musiques/Osirus_Jack/Nicolas.webm', 'musiques\\Tsar_Noir_osirus_jack\\Tsar-Noir.jpg'),

('Ron Van Clief', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:02:59', 'musiques/Osirus_Jack/Ron_Van_Clief.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('T.E.N', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:02:51', 'musiques/Osirus_Jack/T.E.N.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Mazout', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:02:33', 'musiques/Osirus_Jack/Mazout.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Trilogie (feat. Roi Heenok & Kaki Santana 667)', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:01', 'musiques/Osirus_Jack/Trilogie.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('C14', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:21', 'musiques/Osirus_Jack/C14.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Lampadaire, Pt. 2 (feat. Freeze Corleone)', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:27', 'musiques/Osirus_Jack/Lampadaire_Pt_2.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Nowitzki', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:05', 'musiques/Osirus_Jack/Nowitzki.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Or/Mif', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:13', 'musiques/Osirus_Jack/Or_Mif.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Plan De Match (feat. Afro S)', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:54', 'musiques/Osirus_Jack/Plan_De_Match.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Apollo 11', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:52', 'musiques/Osirus_Jack/Apollo_11.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Desert Storm (feat. Dubble G Kiluavi)', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:03:41', 'musiques/Osirus_Jack/Desert_Storm.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
('Vril 67', 'Osirus Jack', 'French music', 'Nouvelle Ère', 'webm', NULL, 'En stock', '00:02:39', 'musiques/Osirus_Jack/Vril_67.webm', 'musiques\\nouvelle_ère_osirus_jack\\nouvelle_ère.jpg'),
/*Jul*/
('Amigo', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:05', 'musiques/JuL/Amigo.webm','musiques\\amigo_jul\\amigo.jpg'),
('Henrico', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:50', 'musiques/JuL/Henrico.webm','musiques\\amigo_jul\\amigo.jpg'),
('Délicieuse', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:12', 'musiques/JuL/Delicieuse.webm','musiques\\amigo_jul\\amigo.jpg'),
('Tu mentiras', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:40', 'musiques/JuL/Tu_mentiras.webm','musiques\\amigo_jul\\amigo.jpg'),
('La tête dans les nuages', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:43', 'musiques/JuL/La_tete_dans_les_nuages.webm','musiques\\amigo_jul\\amigo.jpg'),
('Ou lalala', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:36', 'musiques/JuL/Ou_lalala.webm','musiques\\amigo_jul\\amigo.jpg'),
("Je vais t\'oublier (feat. Marwa Loud)", 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:02:55', 'musiques/JuL/Je_vais_t_oublier.webm','musiques\\amigo_jul\\amigo.jpg'),
('Je traîne seul', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:57', 'musiques/JuL/Je_traine_seul.webm','musiques\\amigo_jul\\amigo.jpg'),
("Comme les gens d\'ici", 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:11', 'musiques/JuL/Comme_les_gens_d_ici.webm','musiques\\amigo_jul\\amigo.jpg'),
('Fratellu', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:55', 'musiques/JuL/Fratellu.webm','musiques\\amigo_jul\\amigo.jpg'),
('Madame (feat. Le Rat Luciano)', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:02', 'musiques/JuL/Madame.webm','musiques\\amigo_jul\\amigo.jpg'),
('Le jaloux', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:28', 'musiques/JuL/Le_jaloux.webm','musiques\\amigo_jul\\amigo.jpg'),
('Je ne vous oublie pas', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:43', 'musiques/JuL/Je_ne_vous_oublie_pas.webm','musiques\\amigo_jul\\amigo.jpg'),
('Je ne veux pas partir', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:11', 'musiques/JuL/Je_ne_veux_pas_partir.webm','musiques\\amigo_jul\\amigo.jpg'),
('Samantha (feat. Hors Ligne, Ger, Moubarak, Norey FZ)', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:17', 'musiques/JuL/Samantha.webm','musiques\\amigo_jul\\amigo.jpg'),
('Facilement', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:21', 'musiques/JuL/Facilement.webm','musiques\\amigo_jul\\amigo.jpg'),
('Comme un fou', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:03:16', 'musiques/JuL/Comme_un_fou.webm','musiques\\amigo_jul\\amigo.jpg'),
('Mauvaise Journée', 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:04:32', 'musiques/JuL/Mauvaise_Journee.webm','musiques\\amigo_jul\\amigo.jpg'),
("Temps D\'avant", 'JuL', 'Rap', 'La tête dans les nuages', 'webm', NULL, 'En stock', '00:05:56', 'musiques/JuL/Temps_D_avant.webm','musiques\\amigo_jul\\amigo.jpg'),
/*Jazz*/
/*Diandra Krall*/
('Stop this World', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:01', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\stop_this_world.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('The Girl in the Other Room', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:08', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\the_girl_in_the_other_room.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Temptation', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:29', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\temptation.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Almost Blue', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:07', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\almost_blue.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
("I've Changed My Address", 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:49', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\ive_changed_my_address.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Love Me Like a Man', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:05:52', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\love_me_like_a_man.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
("I'm Pulling Through", 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:05', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\im_pulling_through.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Black Crow', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:04:51', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\black_crow.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Narrow Daylight', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:03:36', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\narrow_daylight.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Abandoned Masquerade', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:05:13', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\abandoned_masquerade.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
("I'm Coming Through", 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:05:10', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\im_coming_through.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),
('Departure Bay', 'Diana Krall', 'Jazz', 'The Girl In The Other Room', 'vinyle', NULL, 'En stock', '00:05:42', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\departure_bay.webm', 'musiques\\The_Girl_In_The_Other_Room_Diana_Krall\\Diana_Krall.jpg.jpg'),

("Let\'s Face The Music And Dance", 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:05:19', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\lets_face_the_music_and_dance.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('Devil May Care', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:03:21', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\devil_may_care.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
("Let\'s Fall In Love", 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:19', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\lets_fall_in_love.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('When I Look In Your Eyes', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:32', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\when_i_look_in_your_eyes.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('Popsicle Toes', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:28', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\popsicle_toes.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
("I\'ve Got You Under My Skin", 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:06:11', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\ive_got_you_under_my_skin.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
("I Can\'t Give You Anything But Love", 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:02:33', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\i_cant_give_you_anything_but_love.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
("I\'ll String Along With You", 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:46', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\ill_string_along_with_you.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('East Of The Sun (West Of The Moon)', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:57', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\east_of_the_sun_west_of_the_moon.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('Pick Yourself Up', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:03:02', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\pick_yourself_up.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('The Best Thing For You', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:02:37', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\the_best_thing_for_you.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('Do It Again', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:04:35', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\do_it_again.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),
('Why Should I Care?', 'Diana Krall', 'Jazz', 'When I Look In Your Eyes', 'vinyle', NULL, 'En stock', '00:03:47', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\why_should_i_care.webm', 'musiques\\When_I_Look_In_Your_Eyes_Diana_Krall\\When_I_Look_in_Your_Eyes.png'),

/*Classique*/
/*Ozzy Osbourne*/
('Over the Mountain', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:04:32', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\over_the_mountain.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('Flying High Again', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:04:45', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\flying_high_again.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
("You Can\'t Kill Rock and Roll", 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:07:00', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\you_cant_kill_rock_and_roll.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('Believer', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:05:17', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\believer.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('Little Dolls', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:05:40', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\little_dolls.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('Tonight', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:05:51', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\tonight.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('S.A.T.O.', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:04:08', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\sato.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),
('Diary of a Madman', 'Ozzy Osbourne', 'Metal', 'Diary of a Madman', 'vinyle', NULL, 'En stock', '00:06:17', 'musiques\\Diary_of_a_Madman_Ozzy_Osbourne\\diary_of_a_madman.webm', 'musiques\\Ozzy_Osbourne_Diary_of_a_Madman\\Ozzy_Osbourne_Diary_of_a_Madman.jpg'),

('The Ultimate Sin', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:03:44', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\the_ultimate_sin.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Secret Loser', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:04:09', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\secret_loser.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Never Know Why', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:04:27', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\never_know_why.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Thank God for the Bomb', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:03:53', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\thank_god_for_the_bomb.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Never', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:04:19', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\never.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Lightning Strikes', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:05:14', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\lightning_strikes.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Killer of Giants', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:05:42', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\killer_of_giants.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Fool Like You', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:05:20', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\fool_like_you.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),
('Shot in the Dark', 'Ozzy Osbourne', 'Metal', 'The Ultimate Sin', 'vinyle', NULL, 'En stock', '00:04:17', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\shot_in_the_dark.webm', 'musiques\\The_Ultimate_Sin_Ozzy_Osbourne\\The_ultimate_sin.jpg'),


/*Brezialian music*/
/*Gal costa*/
('É Luxo Só', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:48', 'musiques\\Gal_Costa\\e_luxo_so.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Já Era Tempo', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:57', 'musiques\\Gal_Costa\\ja_era_tempo.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Camisa Amarela', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:52', 'musiques\\Gal_Costa\\camisa_amarela.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Na Baixa Do Sapateiro', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:13', 'musiques\\Gal_Costa\\na_baixa_do_sapateiro.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Folhas Mortas', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:13', 'musiques\\Gal_Costa\\folhas_mortas.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('No Tabuleiro Da Baiana', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:55', 'musiques\\Gal_Costa\\no_tabuleiro_da_baiana.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Jogada Pelo Mundo', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:45', 'musiques\\Gal_Costa\\jogada_pelo_mundo.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Inquietação', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:42', 'musiques\\Gal_Costa\\inquietacao.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Tu', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:45', 'musiques\\Gal_Costa\\tu.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Faceira', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:58', 'musiques\\Gal_Costa\\faceira.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Novo Amor', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:02:22', 'musiques\\Gal_Costa\\novo_amor.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),
('Aquarela Do Brasil', 'Gal Costa', 'Brazilian music ', 'Aquarela Do Brasil', 'vinyle', NULL, 'En stock', '00:03:31', 'musiques\\Gal_Costa\\aquarela_do_brasil.webm', 'musiques\\Brazilian_music\\Gal_cotsa_aquerela_do_brasil\\Gal_costa.jpg'),

('Baby', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:33', 'musiques\\Gal_Costa\\baby.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Divino Maravilhoso', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:03', 'musiques\\Gal_Costa\\divino_maravilhoso.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Que Pena (Ele Já Não Gosta Mais De Mim)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:35', 'musiques\\Gal_Costa\\que_pena.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Corcovado (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:25', 'musiques\\Gal_Costa\\corcovado_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Você Não Entende Nada', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:52', 'musiques\\Gal_Costa\\voce_nao_entende_nada.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Lágrimas Negras (Vídeo Oficial)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:03', 'musiques\\Gal_Costa\\lagrimas_negras.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Da Maior Importância (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:05:30', 'musiques\\Gal_Costa\\da_maior_importancia_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Coração Vagabundo (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:45', 'musiques\\Gal_Costa\\coracao_vagabundo_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Barato Total (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:01', 'musiques\\Gal_Costa\\barato_total_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Um Dia De Domingo', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:05:37', 'musiques\\Gal_Costa\\um_dia_de_domingo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Samba Do Aviao (Live)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:24', 'musiques\\Gal_Costa\\samba_do_aviao_live.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('One Note Samba (Live)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:02', 'musiques\\Gal_Costa\\one_note_samba_live.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Folhetim', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:30', 'musiques\\Gal_Costa\\folhetim.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Azul', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:44', 'musiques\\Gal_Costa\\azul.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Sua Estupidez', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:27', 'musiques\\Gal_Costa\\sua_estupidez.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Força Estranha', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:35', 'musiques\\Gal_Costa\\forca_estranha.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Balancê', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:09', 'musiques\\Gal_Costa\\balance.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Rainha Do Mar', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:02:49', 'musiques\\Gal_Costa\\rainha_do_mar.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Tuareg', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:24', 'musiques\\Gal_Costa\\tuareg.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Mamãe Coragem', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:02:30', 'musiques\\Gal_Costa\\mamae_coragem.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Festa Do Interior', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:15', 'musiques\\Gal_Costa\\festa_do_interior.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Dê Um Rolê (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:06', 'musiques\\Gal_Costa\\de_um_role_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Meu Nome É Gal', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:46', 'musiques\\Gal_Costa\\meu_nome_e_gal.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Vapor Barato (Ao Vivo)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:08:38', 'musiques\\Gal_Costa\\vapor_barato_ao_vivo.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Índia', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:38', 'musiques\\Gal_Costa\\india.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Flor De Maracujá', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:03:02', 'musiques\\Gal_Costa\\flor_de_maracuja.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Tigresa', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:04:14', 'musiques\\Gal_Costa\\tigresa.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
('Como 2 E 2 (Ao Vivo / Introdução)', 'Gal Costa', 'Brazilian Music', 'As Melhores', 'vinyle', NULL, 'En stock', '00:02:46', 'musiques\\Gal_Costa\\como_2_e_2_ao_vivo_introducao.webm', 'musiques\\Brazilian_music\\Gal_costa_As_melhores\\Gal_costa.jpg'),
/*Elza Soares*/
('Intro: Justiça', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:01:52', 'musiques\\Elza_Soares\\intro_justica.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('No Tempo da Intolerância', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:02:51', 'musiques\\Elza_Soares\\no_tempo_da_intolerancia.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Pra Ver se Melhora', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:03:23', 'musiques\\Elza_Soares\\pra_ver_se_melhora.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Coragem', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:04:00', 'musiques\\Elza_Soares\\coragem.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Te Quiero', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:03:28', 'musiques\\Elza_Soares\\te_quiero.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Rainha Africana', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:03:51', 'musiques\\Elza_Soares\\rainha_africana.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Mulher Pra Mulher (A Voz Triunfal)', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:02:58', 'musiques\\Elza_Soares\\mulher_pra_mulher.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Feminelza', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:03:38', 'musiques\\Elza_Soares\\feminelza.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('Quem Disse?', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:04:13', 'musiques\\Elza_Soares\\quem_disse.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
('No Compasso da Vida', 'Elza Soares', 'Brazilian Music', 'No Tempo da Intolerância', 'vinyle', NULL, 'En stock', '00:04:07', 'musiques\\Elza_Soares\\no_compasso_da_vida.webm', 'musiques\\Brazilian_music\\No_Tempo_da_Intolerancia_Elza_soares\\No_Tempo_da_Intolerancia.jpg'),
/*Afro*/
/*Burna boy*/
('African Giant', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:05', '\\musiques\\Afro\\African_Giant_Burna_boy\\Burna_Boy_African_Giant.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Destiny', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:18', '\\musiques\\Afro\\African_Giant_Burna_boy\\Destiny.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Gum Body (feat. Jorja Smith)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:16', '\\musiques\\Afro\\African_Giant_Burna_boy\\GumBody.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Collateral Damage', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:18', '\\musiques\\Afro\\African_Giant_Burna_boy\\Collateral_Damage.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Secret (feat. Jeremih and Serani)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:23', '\\musiques\\Afro\\African_Giant_Burna_boy\\Secret.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Another Story (feat. M.anifest)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:04:16', '\\musiques\\Afro\\African_Giant_Burna_boy\\Another_Story.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('This Side (feat. YG)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:23', '\\musiques\\Afro\\African_Giant_Burna_boy\\This_Side.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Omo', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:02:28', '\\musiques\\Afro\\African_Giant_Burna_boy\\Omo.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Show & Tell (feat. Future)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:02:43', '\\musiques\\Afro\\African_Giant_Burna_boy\\Show_and_Tell.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Blak Ryno (Skit)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:01:07', '\\musiques\\Afro\\African_Giant_Burna_boy\\Blak_Ryno.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Different (feat. Damian Marley and Angelique Kidjo)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:17', '\\musiques\\Afro\\African_Giant_Burna_boy\\Different.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Wetin Man Go Do', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:09', '\\musiques\\Afro\\African_Giant_Burna_boy\\Wetin_Man_Go _Do.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Spiritual', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:42', '\\musiques\\Afro\\African_Giant_Burna_boy\\Spiritual.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Pull Up', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:08', '\\musiques\\Afro\\African_Giant_Burna_boy\\Pull_Up.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Anybody', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:16', '\\musiques\\Afro\\African_Giant_Burna_boy\\Anybody.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Dangote', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:54', '\\musiques\\Afro\\African_Giant_Burna_boy\\Dangote.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('On The Low', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:23', '\\musiques\\Afro\\African_Giant_Burna_boy\\On_The_Low.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Gbona', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:08', '\\musiques\\Afro\\African_Giant_Burna_boy\\Gbona.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),
('Killin Dem (feat. Zlatan)', 'Burna Boy', 'Afro', 'African Giant', NULL, NULL, NULL, '00:03:38', '\\musiques\\Afro\\African_Giant_Burna_boy\\Killin_Dem.mp3', '\\musiques\\Afro\\African_giant_burna_boy\\Burna_Boy.png'),

('I Told Them (feat. GZA)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:10', 'chemin_vers_audio/I_Told_Them.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Normal', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:02:05', 'chemin_vers_audio/Normal.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('On Form', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:44', 'chemin_vers_audio/On_Form.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Sittin'' On Top Of The World (feat. 21 Savage)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:09', 'chemin_vers_audio/Sittin_On_Top_Of_The_World.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Tested, Approved & Trusted', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:41', 'chemin_vers_audio/Tested_Approved_Trusted.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Cheat On Me (feat. Dave)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:43', 'chemin_vers_audio/Cheat_On_Me.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Virgil', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:01:20', 'chemin_vers_audio/Virgil.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Big 7', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:02:24', 'chemin_vers_audio/Big_7.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Dey Play', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:02:34', 'chemin_vers_audio/Dey_Play.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('City Boys', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:02:34', 'chemin_vers_audio/City_Boys.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Giza (feat. Seyi Vibez)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:00', 'chemin_vers_audio/Giza.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('12 Jewels (feat. RZA)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:00:28', 'chemin_vers_audio/12_Jewels.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('If I’m Lying', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:18', 'chemin_vers_audio/If_Im_Lying.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Thanks (feat. J. Cole)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:03:37', 'chemin_vers_audio/Thanks.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),
('Talibans II (Bonus Track)', 'Burna Boy', 'Afro', 'I Told Them', NULL, NULL, NULL, '00:02:57', 'chemin_vers_audio/Talibans_II.mp3', 'musiques\\Afro\\i_told_them_Burna_boy\\i_told_them.png'),

('Level Up (Twice As Tall) (feat. Youssou N''Dour)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:04:30', 'chemin_vers_audio/Level_Up.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Alarm Clock', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:02:13', 'chemin_vers_audio/Alarm_Clock.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Way Too Big', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:21', 'chemin_vers_audio/Way_Too_Big.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Bebo', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:02:45', 'chemin_vers_audio/Bebo.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Wonderful', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:04:24', 'chemin_vers_audio/Wonderful.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Onyeka (Baby)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:23', 'chemin_vers_audio/Onyeka.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Naughty By Nature (feat. Naughty By Nature)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:36', 'chemin_vers_audio/Naughty_By_Nature.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Comma', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:02:52', 'chemin_vers_audio/Comma.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('No Fit Vex', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:42', 'chemin_vers_audio/No_Fit_Vex.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('23', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:04:07', 'chemin_vers_audio/23.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Time Flies (feat. Sauti Sol)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:45', 'chemin_vers_audio/Time_Flies.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Monsters You Made (feat. Chris Martin)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:38', 'chemin_vers_audio/Monsters_You_Made.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Wetin Dey Sup', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:38', 'chemin_vers_audio/Wetin_Dey_Sup.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Real Life (feat. Stormzy)', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:03:19', 'chemin_vers_audio/Real_Life.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),
('Bank On It', 'Burna Boy', 'Afro', 'Twice as Tall', NULL, NULL, NULL, '00:04:37', 'chemin_vers_audio/Bank_On_It.mp3', 'musiques\\Afro\\Twice_as_tall_Burna_boy\\Twice_as_Tall.jpg'),

('Glory (feat. Ladysmith Black Mambazo)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:52', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Glory.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Science', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:22', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Science.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Cloak & Dagger (feat. J Hus)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:32', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Cloak_and_Dagger.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Kilometre', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:33', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Kilometre.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Jagele', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:03', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Jagele.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Whiskey', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:24', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Whiskey.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Last Last', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:53', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Last_Last.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Different Size (feat. Victony)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:30', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Different_Size.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('It''s Plenty', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:37', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Its_Plenty.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Dirty Secrets', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:32', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Dirty_Secrets.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Toni-Ann Singh (feat. Popcaan)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:56', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Toni-Ann_Singh.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Solid (feat. Blxst & Kehlani)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:16', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Solid.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('For My Hand (feat. Ed Sheeran)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:40', '\\musiques\\Afro\\Love_Damini_Burna_boy\\For_My_Hand.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Rollercoaster (feat. J Balvin)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:08', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Rollercoaster.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Vanilla', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:36', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Vanilla.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Common Person', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:31', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Common_Person.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Wild Dreams (feat. Khalid)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:03:07', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Wild_Dreams.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('How Bad Could It Be', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:04:58', '\\musiques\\Afro\\Love_Damini_Burna_boy\\How_Bad_Could_It_Be.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),
('Love, Damini (feat. Ladysmith Black Mambazo)', 'Burna Boy', 'Afro', 'Love, Damini', NULL, NULL, NULL, '00:02:23', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.mp3', '\\musiques\\Afro\\Love_Damini_Burna_boy\\Love_Damini.png'),

/*Ayra star*/
('The Year I Turned 21', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:44', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\The_Year_I_Turned_21.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Birds Sing of Money (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:44', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Birds_Sing_of_Money.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Goodbye (Warm Up) ft. Asake (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:37', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Goodbye.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Commas (Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:03:29', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Commas.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Woman Commando ft. Anitta & Coco Jones (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:34', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Woman_Commando.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Control (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:36', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Control.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Lagos Love Story (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:31', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Lagos_Love_Story.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Rhythm & Blues', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:25', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Rhythm_&_Blues.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('21 (Official Performance Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:47', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\21.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Last Heartbreak Song ft. Giveon (Official Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:53', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Last_Heartbreak_Song.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Bad Vibes ft. Seyi Vibez (Official Music Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:38', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Bad_Vibes.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Orun (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:15', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Orun.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('Jazzy''s Song (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:02:27', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\Jazzy_Song.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('1942 ft. Milar (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:03:15', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\1942.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),
('The Kids Are Alright (Official Lyric Video)', 'Ayra Starr', 'Afro', 'The Year I Turned 21', 'vinyle', NULL, 'En stock', '00:03:15', 'musiques\\The_Year_I_Turned_21_Ayra_Starr\\The_Kids_Are_Alright.webm', 'musiques\\Afro\\The_year_I_Turned_21_Ayra_Star\\Ayra_Star.png'),

('Cast (Gen Z Anthem) (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:46', 'musiques\\19_&_Dangerous_Ayra_Starr\\Cast_Gen_Z_Anthem.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Fashion Killer (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:59', 'musiques\\19_&_Dangerous_Ayra_Starr\\Fashion_Killer.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Ase (Visualizer)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:47', 'musiques\\19_&_Dangerous_Ayra_Starr\\Ase.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Bloody Samaritan (with Kelly Rowland)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:09', 'musiques\\19_&_Dangerous_Ayra_Starr\\Bloody_Samaritan_Kelly_Rowland.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Lonely Refix (Visualizer)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:42', 'musiques\\19_&_Dangerous_Ayra_Starr\\Lonely_Refix.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Snitch feat. Fousheé (Performance Video)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:15', 'musiques\\19_&_Dangerous_Ayra_Starr\\Snitch_Foushee.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Toxic (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:37', 'musiques\\19_&_Dangerous_Ayra_Starr\\Toxic.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('In Between (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:17', 'musiques\\19_&_Dangerous_Ayra_Starr\\In_Between.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Running (Visualizer)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:23', 'musiques\\19_&_Dangerous_Ayra_Starr\\Running.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Beggie Beggie feat. CKay (Official Music Video)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:04:20', 'musiques\\19_&_Dangerous_Ayra_Starr\\Beggie_Beggie_CKay.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Karma (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:49', 'musiques\\19_&_Dangerous_Ayra_Starr\\Karma.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Bridgertn (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:23', 'musiques\\19_&_Dangerous_Ayra_Starr\\Bridgertn.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Rush (Official Music Video)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:06', 'musiques\\19_&_Dangerous_Ayra_Starr\\Rush.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Skinny Girl Anthem (Visualizer)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:09', 'musiques\\19_&_Dangerous_Ayra_Starr\\Skinny_Girl_Anthem.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Bloody Samaritan (Performance Video)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:03:16', 'musiques\\19_&_Dangerous_Ayra_Starr\\Bloody_Samaritan_Performance.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),
('Amin (Official Audio)', 'Ayra Starr', 'Afro', '19 & Dangerous', 'vinyle', NULL, 'En stock', '00:02:29', 'musiques\\19_&_Dangerous_Ayra_Starr\\Amin.webm', 'musiques\\Afro\\19_&_dangerous_Ayra_star\\dangerous.jpg'),

/*RAGGAE*/
/*Bob Marley*/
('Is This Love? - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:03:52', 'chemin_vers_audio/Is_This_Love.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('No Woman, No Cry - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:07:05', 'chemin_vers_audio/No_Woman_No_Cry.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Could you Be Loved - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:03:56', 'chemin_vers_audio/Could_you_Be_Loved.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Three Little Birds - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:02:59', 'chemin_vers_audio/Three_Little_Birds.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Buffalo Soldier - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:04:21', 'chemin_vers_audio/Buffalo_Soldier.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Get Up, Stand Up. - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:03:17', 'chemin_vers_audio/Get_Up_Stand_Up.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Stir It Up - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:05:32', 'chemin_vers_audio/Stir_It_Up.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('One Love - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:02:52', 'chemin_vers_audio/One_Love.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('I Shot The Sheriff - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:04:44', 'chemin_vers_audio/I_Shot_The_Sheriff.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Waiting In Vain - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:04:15', 'chemin_vers_audio/Waiting_In_Vain.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Redemption Song - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:03:50', 'chemin_vers_audio/Redemption_Song.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Satisfy My Soul - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:04:18', 'chemin_vers_audio/Satisfy_My_Soul.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Exodus - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:07:22', 'chemin_vers_audio/Exodus.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),
('Jammin - (Bob Marley)', 'Bob Marley', 'Raggae', 'Legend', NULL, NULL, NULL, '00:03:13', 'chemin_vers_audio/Jammin.mp3', 'musiques\\Raggae\\Legend_bob_marley\\BobMarley-Legend.jpg'),

('Coming In From The Cold - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:04:31', 'chemin_vers_audio/Coming_In_From_The_Cold.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Real Situation - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:04:54', 'chemin_vers_audio/Real_Situation.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Bad Card - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:02:59', 'chemin_vers_audio/Bad_Card.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('We And Dem - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:13', 'chemin_vers_audio/We_And_Dem.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Work - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:40', 'chemin_vers_audio/Work.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Zion Train - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:34', 'chemin_vers_audio/Zion_Train.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Pimpers Paradise - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:27', 'chemin_vers_audio/Pimpers_Paradise.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Could You Be Loved - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:57', 'chemin_vers_audio/Could_You_Be_Loved.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Forever Loving Jah - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:57', 'chemin_vers_audio/Forever_Loving_Jah.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),
('Redemption Song - Bob Marley', 'Bob Marley', 'Raggae', 'Uprising', NULL, NULL, NULL, '00:03:52', 'chemin_vers_audio/Redemption_Song.mp3', 'musiques\\Raggae\\Uprising_bo_marley\\uprising.jpg'),

('So Much Trouble In The World', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:04:01', 'chemin_vers_audio/So_Much_Trouble_In_The_World.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Zimbabwe', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:52', 'chemin_vers_audio/Zimbabwe.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Top Rankin''', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:12', 'chemin_vers_audio/Top_Rankin.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Babylon System', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:04:22', 'chemin_vers_audio/Babylon_System.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Survival', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:55', 'chemin_vers_audio/Survival.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Africa Unite', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:02:56', 'chemin_vers_audio/Africa_Unite.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('One Drop', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:52', 'chemin_vers_audio/One_Drop.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Ride Natty Ride', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:52', 'chemin_vers_audio/Ride_Natty_Ride.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Ambush In The Night', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:03:13', 'chemin_vers_audio/Ambush_In_The_Night.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Wake Up And Live', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:04:59', 'chemin_vers_audio/Wake_Up_And_Live.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),
('Ride Natty Ride (12" Mix)', 'Bob Marley', 'Raggae', 'So much trouble in the world', NULL, NULL, NULL, '00:06:24', 'chemin_vers_audio/Ride_Natty_Ride_12_Mix.mp3', 'musiques\\Raggae\\so_much_trouble_in_the_world\\so_much.jpg'),

('Chant Down Babylon (1983)', 'Bob Marley', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:02:37', 'chemin_vers_audio/Chant_Down_Babylon.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Buffalo Soldier (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:04:18', 'chemin_vers_audio/Buffalo_Soldier.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Jump Nyabinghi (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:45', 'chemin_vers_audio/Jump_Nyabinghi.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Mix Up, Mix Up (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:05:03', 'chemin_vers_audio/Mix_Up_Mix_Up.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Give Thanks & Praises (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:17', 'chemin_vers_audio/Give_Thanks_And_Praises.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Blackman Redemption (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:34', 'chemin_vers_audio/Blackman_Redemption.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Trench Town (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:13', 'chemin_vers_audio/Trench_Town.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Stiff Necked Fools (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:26', 'chemin_vers_audio/Stiff_Necked_Fools.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('I Know (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:03:21', 'chemin_vers_audio/I_Know.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg'),
('Rastaman Live Up! (1983)', 'Bob Marley ', 'Raggae', 'Bob Marley & The Wailers', NULL, NULL, NULL, '00:05:28', 'chemin_vers_audio/Rastaman_Live_Up.mp3', 'musiques\\Raggae\\bob_marley_and_the_Wailers\\bob_marley_and_the_Wailers.jpg');

INSERT INTO Livre (titre, auteur, genre, format, prix, chemin_livre, disponibilite, evaluation, date_publication, photo_livre)
VALUES 
('Chemins toxiques','Louis Sachar','Fiction','livre electronique',15,'Livres\\Chemins_toxique_Louis_sachar\\Chemins_toxiques.pdf','Disponible',5,'2016-06-08','Livres\\Chemins_toxique_Louis_sachar\\Chemins_toxique.jpg'),
('1984', 'George Orwell', 'Dystopian', 'livre electronique', 15, 'path/to/1984.epub', 'Disponible', 5, '1949-06-08','Livres\\George_Orwell_1984\\1984.jpg'),
('Les Misérables', 'Victor Hugo', 'Fiction historique', 'livre electronique', 20, 'Livres\\victor_hugo_misérable\\[Hugo_Victor]_Les_Miserables.pdf', 'Disponible', 5, '1960-07-11','Livres\\victor_hugo_misérable\\victo_hugo_misérable.jpg'),
("Lettre d'une inconnue", 'Stefan Zweig', 'Nouvelle', 'livre electronique', 10, 'Livres\\lettre-dune-inconnue\\lettre-dune-inconnue.pdf', 'Disponible', 4, '2009-05-06','Livres\\lettre-dune-inconnue\\lettre_inconnue.jpg'),
('La Planète des Singes', 'Pierre Boulle', 'Science-fiction', 'livre electronique', 11.99, 'Livres\\planete_des_singes\\planete_des_singes.jpg', 'Disponible',4, '1963-01-01', 'Livres\\planete_des_singes\\La Planète Des Singes .pdf'),
('L Étranger', 'Albert Camus', 'Fiction philosophique', 'livre electronique', 12, 'Livres\\Camus_L_Etranger\\Camus-L_Etranger.pdf', 'Disponible', 4,'1942-05-19', 'Livres\\Camus_L_Etranger\\Albert_camus_l_etranger.jpg'),
('Juste la fin du monde', 'Jean-Luc Lagarce', 'Drame', 'livre electronique', 7, 'Livres\\jean_luc_lagarce_la_fin_du_monde\\jean_luc_lagarce_la_fin_du_monde.pdf','Disponible', 4, '1990-01-01', 'Livres\\jean_luc_lagarce_la_fin_du_monde\\la_fin_du_mondejpg.jpg'),
('Les Fleurs du mal', 'Charles Baudelaire', 'Poésie', 'livre electronique', 10, 'Livres\\Les_fleurs_du_mal\\Les-Fleurs-du-Mal-Charles-Baudelaire book2.pdf','Disponible', 4.6, '1857-06-25', 'Livres\\Les_fleurs_du_mal\\fleurs_du_mal.jpg'),

('Le Petit Prince', 'Antoine de Saint-Exupéry', 'Fiction', 'livre electronique', 10, 'Livres\\Saint_Exupery_Le_Petit_Prince\\Le_Petit_Prince.pdf', 'Disponible', 4.5, '1943-04-06', 'Livres\\Saint_Exupery_Le_Petit_Prince\\Le_Petit_Prince.jpg'),
('À la recherche du temps perdu', 'Marcel Proust', 'Classique', 'livre electronique', 30, 'Livres\\Proust_A_la_recherche_du_temps_perdu\\A_la_recherche_du_temps_perdu.pdf', 'Disponible', 5, '1913-11-14', 'Livres\\Proust_A_la_recherche_du_temps_perdu\\A_la_recherche_du_temps_perdu.jpg'),
('Don Quichotte', 'Miguel de Cervantes', 'Classique', 'livre electronique', 15, 'Livres\\Cervantes_Don_Quichotte\\Don_Quichotte.pdf', 'Disponible', 4.8, '1605-01-16', 'Livres\\Cervantes_Don_Quichotte\\Don_Quichotte.jpg'),
('Guerre et Paix', 'Léon Tolstoï', 'Fiction historique', 'livre electronique', 22, 'Livres\\Tolstoi_Guerre_et_Paix\\Guerre_et_Paix.pdf', 'Disponible', 4.9, '1869-01-01', 'Livres\\Tolstoi_Guerre_et_Paix\\Guerre_et_Paix.jpg'),
('Orgueil et Préjugés', 'Jane Austen', 'Romance', 'livre electronique', 12, 'Livres\\Austen_Orgueil_et_Prejuges\\Orgueil_et_Prejuges.pdf', 'Disponible', 4.7, '1813-01-28', 'Livres\\Austen_Orgueil_et_Prejuges\\Orgueil_et_Prejuges.jpg'),
('Moby Dick', 'Herman Melville', 'Aventure', 'livre electronique', 18, 'Livres\\Melville_Moby_Dick\\Moby_Dick.pdf', 'Disponible', 4.6, '1851-11-14', 'Livres\\Melville_Moby_Dick\\Moby_Dick.jpg'),
 
("Harry Potter à l\'école des sorciers", 'J.K. Rowling', 'Fantasy', 'livre electronique', 20, 'Livres\\Rowling_Harry_Potter_1\\Harry_Potter_a_l_ecole_des_sorciers.pdf', 'Disponible', 5, '1997-06-26', 'Livres\\Rowling_Harry_Potter_1\\Harry_Potter.jpg'),
('Le Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'livre electronique', 18, 'Livres\\Tolkien_Le_Hobbit\\Le_Hobbit.pdf', 'Disponible', 4.8, '1937-09-21', 'Livres\\Tolkien_Le_Hobbit\\Le_Hobbit.jpg'),
("L\'Épée de Vérité", 'Terry Goodkind', 'Fantasy', 'livre electronique', 22, 'Livres\\Goodkind_L_Epee_de_Verite\\L_Epee_de_Verite.pdf', 'Disponible', 4.7, '1994-08-15', 'Livres\\Goodkind_L_Epee_de_Verite\\L_Epee_de_Verite.jpg'),
('La Roue du Temps', 'Robert Jordan', 'Fantasy', 'livre electronique', 28, 'Livres\\Jordan_La_Roue_du_Temps\\La_Roue_du_Temps.pdf', 'Disponible', 4.9, '1990-01-15', 'Livres\\Jordan_La_Roue_du_Temps\\La_Roue_du_Temps.jpg'),
('Le Trône de Fer', 'George R.R. Martin', 'Fantasy', 'livre electronique', 25, 'Livres\\Martin_Le_Trone_de_Fer\\Le_Trone_de_Fer.pdf', 'Disponible', 4.8, '1996-08-06', 'Livres\\Martin_Le_Trone_de_Fer\\Le_Trone_de_Fer.jpg'),
("L\'Assassin Royal", 'Robin Hobb', 'Fantasy', 'livre electronique', 20, 'Livres\\Hobb_L_Assassin_Royal\\L_Assassin_Royal.pdf', 'Disponible', 4.7, '1995-03-01', 'Livres\\Hobb_L_Assassin_Royal\\L_Assassin_Royal.jpg'),
('La Belgariade', 'David Eddings', 'Fantasy', 'livre electronique', 24, 'Livres\\Eddings_La_Belgariade\\La_Belgariade.pdf', 'Disponible', 4.6, '1982-01-01', 'Livres\\Eddings_La_Belgariade\\La_Belgariade.jpg');


/**('Le Père Goriot', 'Honoré de Balzac', 'Fiction', 'livre electronique', 14.00, 'En stock', 4.7, '1835-01-01', '../Arcadia/livre/balzac_le_pere_goriot'),
('Moby Dick', 'Herman Melville', 'Adventure', 'audio book', 25, 'path/to/mobydick.mp3', 'Disponible', 4, '1851-11-14','Livres\\George_Orwell_1984\\1984.png'),
('Pride and Prejudice', 'Jane Austen', 'Romance', 'livre electronique', 18, 'path/to/prideandprejudice.epub', 'Disponible', 5, '1813-01-28','Livres\\George_Orwell_1984\\1984.png'),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'audio book', 22, 'path/to/thehobbit.mp3', 'Disponible', 5, '1937-09-21','Livres\\George_Orwell_1984\\1984.png'),
('War and Peace', 'Leo Tolstoy', 'Historical', 'livre electronique', 30, 'path/to/warandpeace.epub', 'Disponible', 5, '1869-01-01','Livres\\George_Orwell_1984\\1984.png'),
('The Catcher in the Rye', 'J.D. Salinger', 'Literature', 'audio book', 18, 'path/to/thecatcherintherye.mp3', 'Disponible', 4, '1951-07-16','Livres\\George_Orwell_1984\\1984.png'),
('Brave New World', 'Aldous Huxley', 'Science Fiction', 'livre electronique', 14, 'path/to/bravenewworld.epub', 'Disponible', 5, '1932-08-18','Livres\\George_Orwell_1984\\1984.png'),

**/
INSERT INTO Evenement (titre, lieu, adresse, date_heure, description, prix_entre, disponibilite_billets, type_evenement, Organisateur_evt)
VALUES 
('Concert de Jazz', 'Théâtre National', '123 Rue de la Musique, Paris', '2024-09-15 20:00:00', 'Un concert de jazz avec des artistes de renommée internationale', 50, 200, 'Musique', 'Jazz Productions'),
('Conférence Tech', 'Centre des Congrès', '456 Avenue de l Innovation, Lyon', '2024-10-05 09:00:00', 'Une conférence sur les dernières innovations technologiques', 100, 500, 'Conférence', 'Tech Innovators Inc.'),
('Exposition d Art Contemporain', 'Musée d Art Moderne', '789 Boulevard des Arts, Marseille', '2024-11-20 10:00:00', 'Une exposition mettant en valeur les œuvres des artistes contemporains', 25, 300, 'Exposition', 'ArtExpo Ltd.'),
('Festival du Film', 'Cinéma Lumière', '321 Rue du Cinéma, Nice', '2024-08-30 18:00:00', 'Projection de films indépendants du monde entier', 15, 150, 'Festival', 'Indie Film Association'),
('Gala de Charité', 'Hôtel de Ville', '654 Place de la République, Bordeaux', '2024-12-01 19:30:00', 'Un gala pour collecter des fonds pour des œuvres caritatives', 200, 100, 'Charité', 'Charity Foundation');


